name: Assertion Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'Code/src/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Code/src/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # Rende visibile il package "src" che sta in Code/src
      PYTHONPATH: Code
      # I tuoi test impostano già SEED, ma non guasta avere un default
      SEED: "314"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # stabile per numba/sklearn; puoi alzare se lo desideri

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (requirements.txt if present)
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install numpy scikit-learn pytest numba matplotlib
          fi

      - name: Run tests
        run: |
          pytest Code/src/tests/tests.py -q
